export const clients = [
  { id: "3", value: "SIMONAGGIO (METALÚRGICA SIMONAGGIO LTDA)" },
  {
    id: "4",
    value: "EXTRUSA PACK (EXPK INDUSTRIA E COMERCIO DE EMBALAGENS LTDA)",
  },
  { id: "5", value: "PLASNEW UTILIDADES DOMÉSTICAS LTDA" },
  { id: "7", value: "PLASUTIL INDUSTRIA E COMERCIO DE PLASTICOS LTDA" },
  { id: "12", value: "FORTALEZA (NEVIO & MOYA ARTEFATOS DE ALUMINIO LTDA)" },
  {
    id: "19",
    value: "ALUMILESTE (ALFA SEVEN EMBALAGENS INDUSTRIA E COMERCIO LTDA)",
  },
  { id: "32", value: "DADU (IND E COM DE PAPEIS DADUPACK LTDA)" },
  { id: "33", value: "DANNY (DVT COMERCIO, IMPORTACAO E EXPORTACAO LTDA)" },
  { id: "35", value: "DPG - PLASTICOS GONCALVES LTDA" },
  { id: "41", value: "GALVANOTEK EMBALAGENS LTDA" },
  {
    id: "51",
    value:
      "OSRAM - (LEDVANCE BRASIL COMÉRCIO DE PRODUTOS ELETRÔNICOS E SISTEMAS DE ENERGIA LTDA)",
  },
  { id: "67", value: "SOPRANO ELETROMETALURGICA E HIDRAULICA LTDA" },
  { id: "72", value: "THREEBOND DO BRASIL INDUSTRIA E COMERCIO LTDA" },
  { id: "85", value: "OUROLUX COMERCIAL LTDA " },
  { id: "94", value: "TRAMONTINA MOVEIS " },
  { id: "102", value: "PLASTICOS DESCARTAVEIS IND. E COM. LTDA (TRIKTRIK)" },
  {
    id: "104",
    value: "ZPN IND. E COM. DE MATERIAIS ESPORTIVOS LTDA (ALLPHA BOLAS)",
  },
  { id: "114", value: "CELESTE (CELESTE IMPORTAÇÃO E EXPORTAÇÃO LTDA)" },
  { id: "116", value: "BEBIDAS BALY (BEBIDAS GRASSI DO BRASIL LTDA)" },
  { id: "191", value: "PANELUX (ALCAST DO BRASIL)" },
  { id: "194", value: "CICLEY (UTILITY HOUSE ARTEF. EMBAL. LTDA)" },
  { id: "200", value: "KIDS ZONE IMP. E COM. DE BRINQUEDOS LTDA" },
  { id: "222", value: "BASTON (BASTON INDUSTRIA DE AEROSSOIS LTDA)" },
  { id: "245", value: "TRAMONTINA S.A CUTELARIA (UTILIDADES)" },
  {
    id: "248",
    value: "VIZET (LE VUE INDUSTRIA E COMERCIO DE PRODUTOS DE BELEZA LTDA ME)",
  },
  { id: "274", value: "PLÁSTICOS MB (PLASTICOS M B LTDA)" },
  {
    id: "275",
    value:
      "HIGIECARE (CELMAR REPRESENTACOES E COMERCIO DE PRODUTOS ALIMENTICIOS LTDA)",
  },
  { id: "280", value: "BABYGO (CTN INDUSTRIA E COMERCIO DE MANUFATURAS LTDA)" },
  { id: "284", value: "VINHOS PANIZZON (SOCIEDADE DE BEBIDAS PANIZZON)" },
  {
    id: "297",
    value: "BAMBOLA BRINQUEDOS (BAMBOLA INDUSTRIA E COMERCIO DE BRINQUEDOS)",
  },
  { id: "298", value: "TERMOLAR (TERMOLAR SA)" },
];
